use super::HighlightKind;

pub(super) fn classify(kind: &str) -> Option<HighlightKind> {
    match kind {
        "if" | "else" | "for" | "while" | "do" | "switch" | "case" | "return" | "break"
        | "continue" | "goto" => Some(HighlightKind::KeywordControl),
        _ => None,
    }
}

pub(super) fn is_c_keyword(kind: &str) -> bool {
    matches!(
        kind,
        "auto"
            | "break"
            | "case"
            | "char"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extern"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "inline"
            | "int"
            | "long"
            | "register"
            | "restrict"
            | "return"
            | "short"
            | "signed"
            | "sizeof"
            | "static"
            | "struct"
            | "switch"
            | "typedef"
            | "union"
            | "unsigned"
            | "void"
            | "volatile"
            | "while"
            | "_Bool"
            | "_Complex"
            | "_Imaginary"
    )
}

pub(super) fn is_cpp_keyword(kind: &str) -> bool {
    is_c_keyword(kind)
        || matches!(
            kind,
            "alignas"
                | "alignof"
                | "and"
                | "and_eq"
                | "asm"
                | "bitand"
                | "bitor"
                | "bool"
                | "catch"
                | "class"
                | "compl"
                | "concept"
                | "constexpr"
                | "consteval"
                | "constinit"
                | "delete"
                | "dynamic_cast"
                | "explicit"
                | "export"
                | "false"
                | "friend"
                | "mutable"
                | "namespace"
                | "new"
                | "noexcept"
                | "not"
                | "not_eq"
                | "nullptr"
                | "operator"
                | "or"
                | "or_eq"
                | "private"
                | "protected"
                | "public"
                | "reinterpret_cast"
                | "requires"
                | "static_assert"
                | "template"
                | "this"
                | "thread_local"
                | "throw"
                | "true"
                | "try"
                | "typeid"
                | "typename"
                | "using"
                | "virtual"
                | "wchar_t"
                | "xor"
                | "xor_eq"
        )
}

pub(super) fn is_java_keyword(kind: &str) -> bool {
    matches!(
        kind,
        "abstract"
            | "assert"
            | "boolean"
            | "break"
            | "byte"
            | "case"
            | "catch"
            | "char"
            | "class"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extends"
            | "final"
            | "finally"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "implements"
            | "import"
            | "instanceof"
            | "int"
            | "interface"
            | "long"
            | "native"
            | "new"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "return"
            | "short"
            | "static"
            | "strictfp"
            | "super"
            | "switch"
            | "synchronized"
            | "this"
            | "throw"
            | "throws"
            | "transient"
            | "try"
            | "void"
            | "volatile"
            | "while"
            | "true"
            | "false"
            | "null"
            | "record"
            | "sealed"
            | "permits"
            | "var"
            | "yield"
    )
}
